name: Build and deploy ASP.Net Core app to Azure Web App - BeautySpa

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build "BeautySpa/BeautySpa.API.csproj" --configuration Release

      - name: Publish with dotnet
        run: dotnet publish "BeautySpa/BeautySpa.API.csproj" -c Release -o publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BeautySpaAPI20250516125713'  # <== ĐỔI TÊN nếu app bạn khác
          package: publish
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
